AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
Metrics/BlockLength:
  Exclude:
    - 'config/initializers/devise.rb'
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20171216044018_devise_create_users.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20171216044018_devise_create_users.rb'
